#62 tratamiento de los errores en python

#try...except...else...finally

#numero1 = 5
#numero2 = 0
#division = numero1/numero2

try:
    numero1=5
    numero2=0
    division=numero1/numero2
    print(division)
except:
    print("ha habido un error")    